window.__env = {
  SUPABASE_URL: "https://npvujaioewprtutbkvjh.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdnVqYWlvZXdwcnR1dGJrdmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNTE4ODQsImV4cCI6MjA3NjgyNzg4NH0.XnJcerVpDHsqmJ5Piblmj5ta5QoYdWv0DeKflB4SOOk"
};
